### ISSUE TITLE
Missing LICENSE file?

### ISSUE THREAD

**Issue by Chrisimx** [BytePhilHD/ApplyServer#1]
Hi, this code base is currently very actively maintained which I like. One problem I see though is that there is no LICENSE file. Because of that the code is **currently licensed under "All rights reserved" making it impossible for anyone else to contribute**. If it's intended to be like that everything's alright and this issue can be closed, so I just wanna ask whether that's the case.
Thanks in advance for the response, kind regards Christian.

**Comment by BytePhilHD** [comment]
Hi, it is intended like that I think. But thanks for the information!
